theme: just-the-docs
title: Orka
description: Orka is a modern Node.js framework based on koa@2 that comes powered with RabbitMQ, Kafka, MongoDB and Redis integrations out of the box
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

logo: /assets/images/orka-horizontal.svg
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

aux_links:
  "Orka on GitHub":
    - "//github.com/Workable/orka"
    
color_scheme: workable
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"

baseurl: "/orka" # the subpath of your site, e.g. /blog
url: "https://workable.github.io" # the base hostname & protocol for your site, e.g. http://example.com
