name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        mongodb-version: [5.0, 6.0]
        rabbit-version: [3.12.5, 4.2.1]
        redis-version: [7.0]
        kafka-version: [4.1.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start services
        run: docker compose up -d --wait
        env:
          MONGO_VERSION: ${{ matrix.mongodb-version }}
          KAFKA_VERSION: ${{ matrix.kafka-version }}
          REDIS_VERSION: ${{ matrix.redis-version }}
          RABBITMQ_VERSION: ${{ matrix.rabbit-version }}

      - name: Run tests
        run: |
          npm install
          TEST_KAFKA=true npm test

      - name: Stop services
        if: always()
        run: docker compose down -v

  auto_merge_bots:
    needs: build
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve and merge Dependabot PR
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --squash --admin "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.SRE_TOOLS_GIT_ROBOT_GITHUB_TOKEN }}
